---
## Controls Files.
# These are YAML files that hold all the details for running checks.
#
## Uncomment to use different control file paths.
# masterControls: ./cfg/master.yaml
# nodeControls: ./cfg/node.yaml

master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd
    - flanneld
    # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
    - kubernetes

  kubernetes:
    defaultconf: /var/lib/kubernetes/config

  apiserver:
    bins:
      - "kube-apiserver"
      - "hyperkube apiserver"
      - "hyperkube kube-apiserver"
      - "apiserver"
    confs:
      - /var/lib/kubernetes/manifests/kube-apiserver.yaml
      - /var/lib/kubernetes/manifests/kube-apiserver.manifest
      - /var/snap/kube-apiserver/current/args
    defaultconf: /var/lib/kubernetes/manifests/kube-apiserver.yaml

  scheduler:
    bins:
      - "kube-scheduler"
      - "hyperkube scheduler"
      - "hyperkube kube-scheduler"
      - "scheduler"
    confs:
      - /var/lib/kubernetes/manifests/kube-scheduler.yaml
      - /bar/lib/kubernetes/manifests/kube-scheduler.manifest
      - /var/snap/kube-scheduler/current/args
    defaultconf: /var/lib/kubernetes/manifests/kube-scheduler.yaml

  controllermanager:
    bins:
      - "kube-controller-manager"
      - "kube-controller"
      - "hyperkube controller-manager"
      - "hyperkube kube-controller-manager"
      - "controller-manager"
    confs:
      - /var/lib/kubernetes/manifests/kube-controller-manager.yaml
      - /var/lib/kubernetes/manifests/kube-controller-manager.manifest
      - /var/snap/kube-controller-manager/current/args
    defaultconf: /var/lib/kubernetes/manifests/kube-controller-manager.yaml

  etcd:
    optional: true
    bins:
      - "etcd"
    confs:
      - /var/lib/kubernetes/manifests/etcd.yaml
      - /var/lib/kubernetes/manifests/etcd.manifest
      - /etc/etcd/etcd.conf
      - /var/snap/etcd/common/etcd.conf.yml
    defaultconf: /var/lib/kubernetes/manifests/etcd.yaml

  flanneld:
    optional: true
    bins:
      - flanneld
    defaultconf: /etc/sysconfig/flanneld

node:
  components:
    - kubelet
    - proxy
    # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
    - kubernetes

  kubernetes:
    defaultconf: "/var/lib/kubernetes/config"

  kubelet:
    cafile:
      - "/var/lib/kubernetes/pki/ca.crt"
      - "/var/lib/kubernetes/certs/ca.crt"
      - "/var/lib/kubernetes/cert/ca.pem"
    svc: 
      # These paths must also be included
      #  in the 'confs' property below
      - "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
      - "/etc/systemd/system/kubelet.service"
      - "/lib/systemd/system/kubelet.service"
      - "/etc/systemd/system/snap.kubelet.daemon.service"
    bins:
      - "hyperkube kubelet"
      - "kubelet"
    kubeconfig:
      - "/var/lib/kubernetes/kubelet.conf"
      - "/var/lib/kubelet/kubeconfig"
      - "/var/lib/kubernetes/kubelet-kubeconfig"
    confs:
      - "/var/lib/kubelet/config.yaml"
      - "/var/lib/kubernetes/kubelet/kubelet-config.json"
      - "/home/kubernetes/kubelet-config.yaml"
      - "/etc/default/kubelet"
      - "/var/lib/kubelet/kubeconfig"
      - "/var/snap/kubelet/current/args"
      ## Due to the fact that the kubelet might be configured
      ## without a kubelet-config file, we use a work-around
      ## of pointing to the systemd service file (which can also
      ## hold kubelet configuration).
      ## Note: The following paths must match the one under 'svc'
      - "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
      - "/etc/systemd/system/kubelet.service"
      - "/lib/systemd/system/kubelet.service"
      - "/etc/systemd/system/snap.kubelet.daemon.service"
    defaultconf: "/var/lib/kubelet/config.yaml"
    defaultsvc: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    defaultkubeconfig: "/var/lib/kubernetes/kubelet.conf"
    defaultcafile: "/var/lib/kubernetes/pki/ca.crt"

  proxy:
    optional: true
    bins:
      - "kube-proxy"
      - "hyperkube proxy"
      - "hyperkube kube-proxy"
      - "proxy"
    confs:
      - /var/lib/kubernetes/proxy
      - /var/lib/kubernetes/addons/kube-proxy-daemonset.yaml
      - /var/snap/kube-proxy/current/args
    kubeconfig:
      - /var/lib/kubernetes/kubelet-kubeconfig
    svc:
      - "/lib/systemd/system/kube-proxy.service"
    defaultconf: /var/lib/kubernetes/addons/kube-proxy-daemonset.yaml
    defaultkubeconfig: "/var/lib/kubernetes/proxy.conf"
